apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: the-project-claim
      containers:
        - name: todo-app
          image: twodogwalker/todo-app:0.10
          volumeMounts:
          - name: shared-image
            mountPath: /usr/app/static/sharedfiles
      # only necessary when the mount needs to be reactivated
      # initContainers:
      # - name: volume-mount-hack
      #   image: busybox
      #   command: ["sh", "-c", "chmod 777 /usr/app/static/sharedfiles"]
      #   volumeMounts:
      #   - name: shared-image
      #     mountPath: /usr/app/static/sharedfiles