apiVersion: v1
kind: Secret
metadata:
    name: pixabay-apikey
data:
    API_KEY: ENC[AES256_GCM,data:Nr08FnkB8mEWconFQIlLNL9B5kjiFBmQGLZzkHYYHuaz4rVLxyRMGnzSGMX4Xh7QqSs9a/sk6EM=,iv:GZghzwz16in7cRDMyfRFs8+DfrXdrFa0TE22lN7ch9Y=,tag:kU502/KL/QEWv6w6TeKjMA==,type:str]
    #ENC[AES256_GCM,data:lMkRsDQDktJgd02riWO+VASr0gNnYqe19aXAMzpxPebwVqa/vmQLMddo0IC9e5WDJ4AkzlF4GDqODzXpYSz9J1A/uQzSqgV8i2FYP250kOk=,iv:E5JC2/5WhPNQ5LBvnatjlFoDMNLnYdEZn+sjrOL4qts=,tag:EOMImcxDCCFmwJvTD446dA==,type:comment]
    #ENC[AES256_GCM,data:BZeXGxZLttWeg+1kJU+eu++C30hkf19zWqTN1UJwNNWvYa10f0XZoVs+dhL+Atti8+gDh0zycmO1,iv:bNq1zvsdS24Brelb69Ild5X18EOpmc8GNJdghW77tY8=,tag:0LO4ATvj5fklUD0mGTa34Q==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZkNBcm9WenFSZkd6MnJ6
            eVF4d041a3pYN0NmVTk0SnBJMzQxLzNrVFE0Cm93c203MnB1ZG1NQWF3UVpncFpR
            YkVldm9zMFZjZkUrQ0dqbkhuSmt4WDAKLS0tIC9OdW5yZldjNVd1dnQ4c2JzZFZZ
            NzFXMTRaeW9kVkQxNUFjT256eXhSY2cKOg7zZojMFaisKspEZSmcPMOQekfT+D2i
            dDRCaMtmwGoCC2daagAmmjdadNoPy1WcdtDIrbtHTCq0Ph3sRNnm9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mgq9ygh23q0cr00mjn0dfn8msak0apdy0ymjv5k50qzy75zmfkqzjdam4
    encrypted_regex: ^(data)$
    lastmodified: "2026-09-17T17:48:47Z"
    mac: ENC[AES256_GCM,data:dybueUnfapTX68A9TOxlpcLdY0sBkKO1xNsaE7axTN+059j+ckTxtCWpG82RQ1RMzU9uc70XSW31dPhweMDeULMapUJoZx0cOIywiqe9Y+BarhgnVu5a/qIBGPYyOUTEwft4lovA7YR1qgFXIcxLriSFkHns7Ykc17ZSYkoh+oo=,iv:2VYbQ9Tl964m0a6X1YYRauJ0fZE9035la2DkOx8VgNo=,tag:tYkzm1HTtI1zu+05S+X7nQ==,type:str]
    version: 3.13.3
